// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR9GzVWyKFC9QpX2PfZNj6vkL97MaXETo',
    appId: '1:17897348329:web:9ed98913c198cdc0a3a478',
    messagingSenderId: '17897348329',
    projectId: 'quizy-5c4d4',
    authDomain: 'quizy-5c4d4.firebaseapp.com',
    storageBucket: 'quizy-5c4d4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-OdzSq-dquACl507MQjocMoAK1e5x3Rw',
    appId: '1:17897348329:android:6ee180086e5e87e8a3a478',
    messagingSenderId: '17897348329',
    projectId: 'quizy-5c4d4',
    storageBucket: 'quizy-5c4d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzr1Oa9GBniFu4-mwioY_zGJ7meYocQxI',
    appId: '1:17897348329:ios:11e0be45bca4fa28a3a478',
    messagingSenderId: '17897348329',
    projectId: 'quizy-5c4d4',
    storageBucket: 'quizy-5c4d4.firebasestorage.app',
    iosBundleId: 'com.example.quizy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzr1Oa9GBniFu4-mwioY_zGJ7meYocQxI',
    appId: '1:17897348329:ios:11e0be45bca4fa28a3a478',
    messagingSenderId: '17897348329',
    projectId: 'quizy-5c4d4',
    storageBucket: 'quizy-5c4d4.firebasestorage.app',
    iosBundleId: 'com.example.quizy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR9GzVWyKFC9QpX2PfZNj6vkL97MaXETo',
    appId: '1:17897348329:web:d7aa84e5deffe6eda3a478',
    messagingSenderId: '17897348329',
    projectId: 'quizy-5c4d4',
    authDomain: 'quizy-5c4d4.firebaseapp.com',
    storageBucket: 'quizy-5c4d4.firebasestorage.app',
  );
}
